# Rustfmt configuration for lclq

# Edition
edition = "2024"

# Maximum line width
max_width = 100

# Use hard tabs instead of spaces
hard_tabs = false

# Number of spaces per tab
tab_spaces = 4

# Style
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function definitions
fn_single_line = false
where_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"

# Comments
normalize_comments = true
wrap_comments = true
comment_width = 100

# Formatting
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true

# Misc
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_try_shorthand = true
use_field_init_shorthand = true
