# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Security vulnerability database
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    # RSA Marvin attack - sqlx dependency, no fix available yet
    # Medium severity timing attack. We don't use RSA encryption directly.
    "RUSTSEC-2023-0071",
    # proc-macro-error unmaintained - tabled dependency
    # Used only for CLI display, not a security concern
    "RUSTSEC-2024-0370",
]

[licenses]
# License configuration
# Using 'confidence-threshold = 0.8' as the default
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "0BSD",
    "MPL-2.0",
    "Zlib",
]
exceptions = [
    # Add any exceptional licenses here if needed
]

[bans]
# Banned crates
multiple-versions = "warn"
wildcards = "allow"
deny = []

[sources]
# Source configuration
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
